# Generated by Django 3.2.7 on 2021-12-10 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('fname', models.CharField(max_length=30, verbose_name='Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Name')),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('adultos', models.IntegerField()),
                ('ninos', models.IntegerField()),
                ('sencilla', models.IntegerField()),
                ('doble', models.IntegerField()),
                ('triple', models.IntegerField()),
                ('king', models.IntegerField()),
                ('reserva_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_reservada', to='hotelApp.habitacion')),
                ('reserva_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
